//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Primavera.Lithium.ChatGPT.Server.Host.Localization;

#region Code

#region Public Classes

/// <summary>
/// Provides means to access resource strings.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("Lithium", "5")]
public partial class ViewsResources
{
    #region Code

    #region Private Fields

    private static System.Resources.ResourceManager? resourceManager;
    private static System.Globalization.CultureInfo? resourceCulture;

    #endregion

    #region Public Properties

    /// <summary>
    /// Gets the 'RES_NoFeaturesForWebBrowsers' resource string.
    /// </summary>
    public static string RES_NoFeaturesForWebBrowsers => ResourceManager.GetString("RES_NoFeaturesForWebBrowsers", Culture) ?? string.Empty;

    /// <summary>
    /// Gets the 'RES_ClientLibraryDocumentation' resource string.
    /// </summary>
    public static string RES_ClientLibraryDocumentation => ResourceManager.GetString("RES_ClientLibraryDocumentation", Culture) ?? string.Empty;

    /// <summary>
    /// Gets the 'RES_RestApiDocumentation' resource string.
    /// </summary>
    public static string RES_RestApiDocumentation => ResourceManager.GetString("RES_RestApiDocumentation", Culture) ?? string.Empty;

    /// <summary>
    /// Gets the 'RES_WebhooksDocumentation' resource string.
    /// </summary>
    public static string RES_WebhooksDocumentation => ResourceManager.GetString("RES_WebhooksDocumentation", Culture) ?? string.Empty;

    /// <summary>
    /// Gets the 'RES_PageTitle_Error' resource string.
    /// </summary>
    public static string RES_PageTitle_Error => ResourceManager.GetString("RES_PageTitle_Error", Culture) ?? string.Empty;

    /// <summary>
    /// Gets the 'RES_PageTitle_Error_StatusCode' resource string.
    /// </summary>
    public static string RES_PageTitle_Error_StatusCode => ResourceManager.GetString("RES_PageTitle_Error_StatusCode", Culture) ?? string.Empty;

    /// <summary>
    /// Gets the 'RES_Title_Error' resource string.
    /// </summary>
    public static string RES_Title_Error => ResourceManager.GetString("RES_Title_Error", Culture) ?? string.Empty;

    /// <summary>
    /// Gets the 'RES_Title_400' resource string.
    /// </summary>
    public static string RES_Title_400 => ResourceManager.GetString("RES_Title_400", Culture) ?? string.Empty;

    /// <summary>
    /// Gets the 'RES_Title_401' resource string.
    /// </summary>
    public static string RES_Title_401 => ResourceManager.GetString("RES_Title_401", Culture) ?? string.Empty;

    /// <summary>
    /// Gets the 'RES_Title_403' resource string.
    /// </summary>
    public static string RES_Title_403 => ResourceManager.GetString("RES_Title_403", Culture) ?? string.Empty;

    /// <summary>
    /// Gets the 'RES_Title_404' resource string.
    /// </summary>
    public static string RES_Title_404 => ResourceManager.GetString("RES_Title_404", Culture) ?? string.Empty;

    /// <summary>
    /// Gets the 'RES_Title_405' resource string.
    /// </summary>
    public static string RES_Title_405 => ResourceManager.GetString("RES_Title_405", Culture) ?? string.Empty;

    /// <summary>
    /// Gets the 'RES_Title_500' resource string.
    /// </summary>
    public static string RES_Title_500 => ResourceManager.GetString("RES_Title_500", Culture) ?? string.Empty;

    /// <summary>
    /// Gets the 'RES_Title_StatusCode' resource string.
    /// </summary>
    public static string RES_Title_StatusCode => ResourceManager.GetString("RES_Title_StatusCode", Culture) ?? string.Empty;

    /// <summary>
    /// Gets the 'RES_Description_Unexpected' resource string.
    /// </summary>
    public static string RES_Description_Unexpected => ResourceManager.GetString("RES_Description_Unexpected", Culture) ?? string.Empty;

    /// <summary>
    /// Gets the 'RES_Description_400' resource string.
    /// </summary>
    public static string RES_Description_400 => ResourceManager.GetString("RES_Description_400", Culture) ?? string.Empty;

    /// <summary>
    /// Gets the 'RES_Description_401' resource string.
    /// </summary>
    public static string RES_Description_401 => ResourceManager.GetString("RES_Description_401", Culture) ?? string.Empty;

    /// <summary>
    /// Gets the 'RES_Description_403' resource string.
    /// </summary>
    public static string RES_Description_403 => ResourceManager.GetString("RES_Description_403", Culture) ?? string.Empty;

    /// <summary>
    /// Gets the 'RES_Description_404' resource string.
    /// </summary>
    public static string RES_Description_404 => ResourceManager.GetString("RES_Description_404", Culture) ?? string.Empty;

    /// <summary>
    /// Gets the 'RES_Description_405' resource string.
    /// </summary>
    public static string RES_Description_405 => ResourceManager.GetString("RES_Description_405", Culture) ?? string.Empty;

    /// <summary>
    /// Gets the 'RES_Description_500' resource string.
    /// </summary>
    public static string RES_Description_500 => ResourceManager.GetString("RES_Description_500", Culture) ?? string.Empty;

    /// <summary>
    /// Gets the 'RES_Description_StatusCode' resource string.
    /// </summary>
    public static string RES_Description_StatusCode => ResourceManager.GetString("RES_Description_StatusCode", Culture) ?? string.Empty;

    /// <summary>
    /// Gets the 'RES_Description_Unexpected_ErrorId' resource string.
    /// </summary>
    public static string RES_Description_Unexpected_ErrorId => ResourceManager.GetString("RES_Description_Unexpected_ErrorId", Culture) ?? string.Empty;

    /// <summary>
    /// Gets the 'RES_ErrorId' resource string.
    /// </summary>
    public static string RES_ErrorId => ResourceManager.GetString("RES_ErrorId", Culture) ?? string.Empty;

    /// <summary>
    /// Gets the 'RES_SignedInAs' resource string.
    /// </summary>
    public static string RES_SignedInAs => ResourceManager.GetString("RES_SignedInAs", Culture) ?? string.Empty;

    /// <summary>
    /// Gets the 'RES_Version' resource string.
    /// </summary>
    public static string RES_Version => ResourceManager.GetString("RES_Version", Culture) ?? string.Empty;

    /// <summary>
    /// Gets the 'RES_Build' resource string.
    /// </summary>
    public static string RES_Build => ResourceManager.GetString("RES_Build", Culture) ?? string.Empty;

    #endregion

    #region Internal Properties

    /// <summary>
    /// Gets the resource manager.
    /// </summary>
    internal static System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (resourceManager == null)
            {
                resourceManager = new System.Resources.ResourceManager("Primavera.Lithium.ChatGPT.Server.Host.GeneratedCode.ViewsResources.gen", typeof(ViewsResources).Assembly);
            }
            
            return resourceManager;
        }
    }

    /// <summary>
    /// Gets or sets the culture.
    /// </summary>
    internal static System.Globalization.CultureInfo? Culture
    {
        get
        {
            return resourceCulture;
        }
        set
        {
            resourceCulture = value;
        }
    }

    #endregion

    #region Public Constructors

    /// <summary>
    /// Initializes a new instance of the <see cref="ViewsResources"/> class.
    /// </summary>
    public ViewsResources()
    {
    }

    #endregion

    #endregion
}

#endregion

#endregion
