//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Primavera.Lithium.ChatGPT.Server.RestApi.Controllers;

#region Code

#region Public Interfaces

/// <summary>
/// The chatGPT controller.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("Lithium", "5")]
public partial interface IChatGPTController
{
    #region Code

    #region Methods

    /// <summary>
    /// Ask a question to the chat.
    /// </summary>
    /// <param name="request">The request with the question.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>
    /// The chat response.
    /// </returns>
    System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.IActionResult> AskAsync(Primavera.Lithium.ChatGPT.Server.RestApi.Models.Request request, System.Threading.CancellationToken cancellationToken = default);

    #endregion

    #endregion
}

#endregion

#endregion
