//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Primavera.Lithium.ChatGPT.Server.RestApi;

#region Code

#region Internal Classes

/// <summary>
/// Defines the base class of the mapping profile
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("Lithium", "5")]
internal abstract partial class MappingProfileBase : AutoMapper.Profile
{
    #region Code

    #region Protected Constructors

    /// <summary>
    /// Initializes a new instance of the <see cref="MappingProfileBase" /> class.
    /// </summary>
    protected MappingProfileBase()
    {
        this.InitializeMappings();
    }

    #endregion

    #region Protected Methods

    /// <summary>
    /// Initializes the mappings.
    /// </summary>
    protected virtual void InitializeMappings()
    {
    }

    #endregion

    #endregion
}

/// <summary>
/// Defines the mapping profile.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("Lithium", "5")]
internal partial class MappingProfile : MappingProfileBase
{
    #region Code

    #region Public Constructors

    /// <summary>
    /// Initializes a new instance of the <see cref="MappingProfile" /> class.
    /// </summary>
    public MappingProfile()
        : base()
    {
    }

    #endregion

    #endregion
}

#endregion

#endregion
