//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Primavera.Lithium.ChatGPT.Server.RestApi.Localization;

#region Code

#region Public Classes

/// <summary>
/// Provides means to access resource strings.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("Lithium", "5")]
public partial class ModelsResources
{
    #region Code

    #region Private Fields

    private static System.Resources.ResourceManager? resourceManager;
    private static System.Globalization.CultureInfo? resourceCulture;

    #endregion

    #region Public Properties

    /// <summary>
    /// Gets the 'RES_Display_Request_Question' resource string.
    /// </summary>
    public static string RES_Display_Request_Question => ResourceManager.GetString("RES_Display_Request_Question", Culture) ?? string.Empty;

    #endregion

    #region Internal Properties

    /// <summary>
    /// Gets the resource manager.
    /// </summary>
    internal static System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (resourceManager == null)
            {
                resourceManager = new System.Resources.ResourceManager("Primavera.Lithium.ChatGPT.Server.RestApi.GeneratedCode.ModelsResources.gen", typeof(ModelsResources).Assembly);
            }
            
            return resourceManager;
        }
    }

    /// <summary>
    /// Gets or sets the culture.
    /// </summary>
    internal static System.Globalization.CultureInfo? Culture
    {
        get
        {
            return resourceCulture;
        }
        set
        {
            resourceCulture = value;
        }
    }

    #endregion

    #region Public Constructors

    /// <summary>
    /// Initializes a new instance of the <see cref="ModelsResources"/> class.
    /// </summary>
    public ModelsResources()
    {
    }

    #endregion

    #endregion
}

#endregion

#endregion
