//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Primavera.Lithium.ChatGPT.Server.RestApi.Metadata;

#region Code

#region Internal Classes

/// <summary>
/// Defines constants that specify the routes used by the REST API actions.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("Lithium", "5")]
internal static partial class Routes
{
    #region Code

    #region Internal Classes

    /// <summary>
    /// Defines constants that specify the routes used by the ChatGPT actions.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Lithium", "5")]
    internal static partial class ChatGPT
    {
        #region Code

        #region Internal Constants

        /// <summary>
        /// Defines the route for the following action: ChatGPT#Ask.
        /// </summary>
        internal const string Ask = "/api/v{version:apiVersion}/chatgpt";

        #endregion

        #endregion
    }

    #endregion

    #endregion
}

#endregion

#endregion
