//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;
using System.Resources;

// Ignore Spelling: Lithium
// Ignore Spelling: Grupo Primavera
// Ignore Spelling: Copyright © 2018-2023 Grupo Primavera
// Ignore Spelling: Grupo Primavera

[assembly: AssemblyTitle("Lithium Chat Gpt Service REST API Tests")]
[assembly: AssemblyDescription("Class library that provides unit tests.")]

[assembly: AssemblyProduct("Lithium")]

[assembly: AssemblyCompany("Grupo Primavera")]
[assembly: AssemblyCopyright("Copyright © 2018-2023 Grupo Primavera")]
[assembly: AssemblyTrademark("Grupo Primavera")]
[assembly: NeutralResourcesLanguage("en-US")]

[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]

[assembly: AssemblyInformationalVersion("*development*")]
