//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primavera.Lithium.ChatGPT.Server.RestApi.Tests.Models;

#region Code

#region Public Classes

/// <summary>
/// Defines the base class for tests on SerializerContext.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("Lithium", "5")]
public abstract partial class SerializerContextTestsBase
{
    #region Code

    #region Public Methods

    /// <summary>
    /// Tests the serialization of <see cref="Primavera.Lithium.ChatGPT.Server.RestApi.Models.Request"/>.
    /// </summary>
    [Xunit.Fact]
    public virtual void SerializerContext_Request_Serialization()
    {
        Primavera.Lithium.ChatGPT.Server.RestApi.Models.Request instance = this.CreateDefaultRequest();

        System.Text.Json.JsonSerializerOptions options = this.GetJsonSerializerOptions();

        string json = System.Text.Json.JsonSerializer.Serialize(instance, options);
        json.Should().NotBeEmpty();

        Primavera.Lithium.ChatGPT.Server.RestApi.Models.Request deserialized = System.Text.Json.JsonSerializer.Deserialize<Primavera.Lithium.ChatGPT.Server.RestApi.Models.Request>(json, options);
        deserialized.Should().NotBeNull();
    }

    #endregion

    #region Protected Methods

    /// <summary>
    /// Initializes a default instance of <see cref="Primavera.Lithium.ChatGPT.Server.RestApi.Models.Request"/>.
    /// </summary>
    protected virtual Primavera.Lithium.ChatGPT.Server.RestApi.Models.Request CreateDefaultRequest()
    {
        Primavera.Lithium.ChatGPT.Server.RestApi.Models.Request result = new Primavera.Lithium.ChatGPT.Server.RestApi.Models.Request();

        result.Question = "value";

        return result;
    }

    /// <summary>
    /// Retrieves a default instance of System.Text.Json.JsonSerializerOptions.
    /// </summary>
    protected virtual System.Text.Json.JsonSerializerOptions GetJsonSerializerOptions()
    {
        System.Text.Json.JsonSerializerOptions result = new System.Text.Json.JsonSerializerOptions()
        {
            DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull
        };

        result.AddContext<Primavera.Lithium.ChatGPT.Server.RestApi.Models.SerializerContext>();

        return result;
    }

    #endregion

    #endregion
}

/// <summary>
/// Provides tests for the SerializerContext type.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("Lithium", "5")]
public partial class SerializerContextTests : SerializerContextTestsBase
{
    #region Code

    #endregion
}

#endregion

#endregion
