//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primavera.Lithium.ChatGPT.Server.RestApi.Tests;

#region Code

#region Public Classes

/// <summary>
/// Defines the base class for <see cref="StartupTests"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("Lithium", "5")]
public abstract partial class StartupTestsBase
{
    #region Code

    #region Protected Methods

    /// <summary>
    /// Creates the service collection instance.
    /// </summary>
    /// <returns>
    /// The service collection.
    /// </returns>
    protected virtual Microsoft.Extensions.DependencyInjection.ServiceCollection CreateServiceCollection()
    {
        return new Microsoft.Extensions.DependencyInjection.ServiceCollection();
    }

    /// <summary>
    /// Tests the AddRestApiPart method.
    /// </summary>
    protected virtual void TestAddRestApiPart()
    {
        Primavera.Lithium.ChatGPT.Server.Common.Configuration.HostConfiguration hostConfiguration = new Primavera.Lithium.ChatGPT.Server.Common.Configuration.HostConfiguration();

        Microsoft.Extensions.DependencyInjection.ServiceCollection services = this.CreateServiceCollection();

        Microsoft.Extensions.DependencyInjection.IMvcBuilder builder = services.AddMvc();

        builder.AddRestApiPart(hostConfiguration);

        System.IServiceProvider provider = services.BuildServiceProvider();

        provider.Should().HaveSingleton<AutoMapper.Profile>()
            .Which.Should().BeOfType<MappingProfile>();

        this.TestAddRestApiPartServices(services, provider);
    }

    /// <summary>
    /// Tests the services registered in the AddRestApiPart method.
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <param name="provider">The service provider.</param>
    protected virtual void TestAddRestApiPartServices(Microsoft.Extensions.DependencyInjection.IServiceCollection services, System.IServiceProvider provider)
    {
    }

    #endregion

    #endregion
}

/// <summary>
/// Provides integration tests for <see cref="Startup"/>.
/// </summary>
/// <seealso cref="StartupTests" />
[System.CodeDom.Compiler.GeneratedCode("Lithium", "5")]
public sealed partial class StartupTests : StartupTestsBase
{
    #region Code

    #region Public Constructors

    /// <summary>
    /// Initializes a new instance of the <see cref="StartupTests"/> class.
    /// </summary>
    public StartupTests()
        : base()
    {
    }

    #endregion

    #region Public Methods

    /// <summary>
    /// Tests the AddRestApiPart method.
    /// </summary>
    [Fact]
    public void StartupTests_AddRestApiPart()
    {
        this.TestAddRestApiPart();
    }

    #endregion

    #endregion
}

#endregion

#endregion
