//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Primavera.Lithium.ChatGPT.Client.Rest.Models;

#region Code

#region Public Classes

/// <summary>
/// Defines the base class for <see cref="Request"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("Lithium", "5")]
public abstract partial class RequestBase
{
    #region Code

    #region Public Properties

    /// <summary>
    /// The question.
    /// </summary>
    [Primavera.Hydrogen.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = false)]
    [System.ComponentModel.DataAnnotations.Display(Name = nameof(Localization.ModelsResources.RES_Display_Request_Question), ResourceType = typeof(Localization.ModelsResources))]
    [System.Diagnostics.CodeAnalysis.MaybeNull]
    [System.Text.Json.Serialization.JsonPropertyName("question")]
    public virtual string Question
    {
        get;
        set;
    }

    #endregion

    #region Protected Constructors

    /// <summary>
    /// Initializes a new instance of the <see cref="RequestBase"/> class.
    /// </summary>
    protected RequestBase()
    {
        // Initialize default values

        this.SetDefaultValues();
    }

    #endregion

    #region Protected Methods

    /// <summary>
    /// Sets the default values.
    /// </summary>
    /// <remarks>
    /// This method should be overridden to set the default values of properties.
    /// </remarks>
    protected virtual void SetDefaultValues()
    {
    }

    #endregion

    #endregion
}

/// <summary>
/// The request resource.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("Lithium", "5")]
public partial class Request : RequestBase
{
    #region Code

    #region Public Constructors

    /// <summary>
    /// Initializes a new instance of the <see cref="Request"/> class.
    /// </summary>
    public Request()
        : base()
    {
    }

    #endregion

    #endregion
}

#endregion

#region Internal Classes

/// <summary>
/// Defines the serializer context.
/// </summary>
[System.Text.Json.Serialization.JsonSerializable(typeof(Primavera.Lithium.ChatGPT.Client.Rest.Models.Request))]
[System.Text.Json.Serialization.JsonSerializable(typeof(System.Collections.Generic.IEnumerable<Primavera.Lithium.ChatGPT.Client.Rest.Models.Request>))]
[System.Text.Json.Serialization.JsonSerializable(typeof(System.Collections.Generic.IList<Primavera.Lithium.ChatGPT.Client.Rest.Models.Request>))]
[System.Text.Json.Serialization.JsonSerializable(typeof(System.Collections.Generic.List<Primavera.Lithium.ChatGPT.Client.Rest.Models.Request>))]
internal partial class SerializerContext : System.Text.Json.Serialization.JsonSerializerContext
{
    #region Code

    #endregion
}

#endregion

#endregion
