//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Primavera.Lithium.ChatGPT.Client.Rest.Metadata;

#region Code

#region Internal Classes

/// <summary>
/// Defines constants that specify the routes used by the REST API actions.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("Lithium", "5")]
internal static partial class Routes
{
    #region Code

    #region Internal Classes

    /// <summary>
    /// Defines constants that specify the routes used by the monitoring actions.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Lithium", "5")]
    internal static partial class Monitoring
    {
        #region Code

        #region Internal Constants

        /// <summary>
        /// Defines the route for the action that probes the service. This action is used to perform dependencies tests on the service.
        /// </summary>
        internal const string Probe = ".monitoring/probe";

        /// <summary>
        /// Defines the route for the action that diagnoses the service. This action is used to perform functional tests on the service.
        /// </summary>
        internal const string Diagnostics = ".monitoring/diagnostics";

        /// <summary>
        /// Defines the route for the action that analyzes the endpoints of the service. This action is used to verify the service implementation.
        /// </summary>
        internal const string Endpoints = ".monitoring/endpoints";

        /// <summary>
        /// Defines the route for the action that analyzes the configuration of the service. This action is used to verify the service implementation.
        /// </summary>
        internal const string Configuration = ".monitoring/configuration";

        /// <summary>
        /// Defines the route for the action that returns information about of the service.
        /// </summary>
        internal const string Information = ".monitoring/info";

        #endregion

        #endregion
    }

    /// <summary>
    /// Defines constants that specify the routes used by the ChatGPT actions.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Lithium", "5")]
    internal static partial class ChatGPT
    {
        #region Code

        #region Internal Constants

        /// <summary>
        /// Defines the route for the following action: ChatGPT#Ask.
        /// </summary>
        internal const string Ask = "/api/v{version:apiVersion}/chatgpt";

        #endregion

        #endregion
    }

    #endregion

    #endregion
}

#endregion

#endregion
