//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Primavera.Lithium.ChatGPT.Client.Rest;

#region Code

#region Internal Classes

/// <summary>
/// Defines a factory to resolve <see cref="ChatGPTClient"/> instances.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("Lithium", "5")]
internal partial class ChatGPTClientFactory : Primavera.Hydrogen.Rest.Client.RestServiceClientFactory<ChatGPTClient, ChatGPTClientOptions>
{
    #region Code

    #region Public Constructors

    /// <summary>
    /// Initializes a new instance of the <see cref="ChatGPTClientFactory" /> class.
    /// </summary>
    /// <param name="serviceProvider">The service provider.</param>
    public ChatGPTClientFactory(System.IServiceProvider serviceProvider)
        : base(serviceProvider)
    {
    }

    #endregion

    #endregion
}

#endregion

#endregion
