//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Primavera.Lithium.ChatGPT.Server.Common;

#region Code

#region Public Classes

/// <summary>
/// Defines constants that specify application error codes.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("Lithium", "5")]
public static partial class ErrorCodes
{
    #region Code

    #region Public Constants

    /// <summary>
    /// The request arguments are invalid.
    /// </summary>
    public const string RequestArgsInvalid = nameof(RequestArgsInvalid);

    #endregion

    #endregion
}

#endregion

#endregion
