//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Primavera.Lithium.ChatGPT.Server.Common;

#region Code

#region Public Classes

/// <summary>
/// Provides extension methods for the IServiceCollection type.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("Lithium", "5")]
public static partial class ServiceCollectionExtensions
{
    #region Code

    #region Public Methods

    /// <summary>
    /// Configures the common part.
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <param name="hostConfiguration">The host configuration.</param>
    /// <returns>
    /// The service collection instance.
    /// </returns>
    /// <remarks>
    /// This method is called from the host startup.
    /// </remarks>
    public static Microsoft.Extensions.DependencyInjection.IServiceCollection AddCommonPart(this Microsoft.Extensions.DependencyInjection.IServiceCollection services, Primavera.Lithium.ChatGPT.Server.Common.Configuration.HostConfiguration hostConfiguration)
    {
        Primavera.Lithium.ChatGPT.Server.Common.Startup instance = new Primavera.Lithium.ChatGPT.Server.Common.Startup(hostConfiguration);

        instance
            .AddServices(services);

        instance
            .AddMapper(services);

        return services;
    }

    #endregion

    #endregion
}

#endregion

#region Internal Classes

/// <summary>
/// Defines the base class for <see cref="Startup" /> to allow customization.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("Lithium", "5")]
internal abstract partial class StartupBase
{
    #region Code

    #region Protected Properties

    /// <summary>
    /// Gets the host configuration.
    /// </summary>
    protected Primavera.Lithium.ChatGPT.Server.Common.Configuration.HostConfiguration HostConfiguration
    {
        get;
    }

    #endregion

    #region Protected Constructors

    /// <summary>
    /// Initializes a new instance of the <see cref="StartupBase" /> class.
    /// </summary>
    /// <param name="hostConfiguration">The host configuration.</param>
    protected StartupBase(Primavera.Lithium.ChatGPT.Server.Common.Configuration.HostConfiguration hostConfiguration)
    {
        this.HostConfiguration = hostConfiguration;
    }

    #endregion

    #region Internal Methods

    /// <summary>
    /// Configures the services.
    /// </summary>
    /// <param name="services">The service collection.</param>
    internal virtual void AddServices(Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
        services
            .AddLogging();
    }

    /// <summary>
    /// Configures the mapper.
    /// </summary>
    /// <param name="services">The service collection.</param>
    internal virtual void AddMapper(Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
        services
            .AddAutoMapper(
                (provider, options) =>
                {
                    System.Collections.Generic.IEnumerable<AutoMapper.Profile> profiles = provider.GetServices<AutoMapper.Profile>();

                    foreach (AutoMapper.Profile profile in profiles)
                    {
                        options.AddProfile(profile);
                    }
                },
                assemblies: null);
    }

    #endregion

    #endregion
}

/// <summary>
/// Provides methods to startup the common part.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("Lithium", "5")]
internal partial class Startup : StartupBase
{
    #region Code

    #region Public Constructors

    /// <summary>
    /// Initializes a new instance of the <see cref="Startup" /> class.
    /// </summary>
    /// <param name="hostConfiguration">The host configuration.</param>
    public Startup(Primavera.Lithium.ChatGPT.Server.Common.Configuration.HostConfiguration hostConfiguration)
        : base(hostConfiguration)
    {
    }

    #endregion

    #endregion
}

#endregion

#endregion
