//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Primavera.Lithium.ChatGPT.Client.Console.Configuration;

#region Code

#region Internal Classes

/// <summary>
/// Defines the base class for the configuration used by the application.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("Lithium", "5")]
internal abstract partial class ApplicationConfigurationBase
{
    #region Code

    #region Public Properties

    /// <summary>
    /// Gets or sets the service base URI.
    /// </summary>
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings")]
    public virtual string? ServiceBaseUri
    {
        get;
        set;
    }

    /// <summary>
    /// Gets or sets the environments configuration.
    /// </summary>
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings")]
    public virtual System.Collections.Generic.IDictionary<string, EnvironmentConfiguration>? Environments
    {
        get;
        set;
    }

    #endregion

    #region Protected Constructors

    /// <summary>
    /// Initializes a new instance of the <see cref="ApplicationConfigurationBase"/> class.
    /// </summary>
    protected ApplicationConfigurationBase()
    {
        this.Environments = new System.Collections.Generic.Dictionary<string, EnvironmentConfiguration>(System.StringComparer.OrdinalIgnoreCase);

        this.SetDefaultValues();
    }

    #endregion

    #region Protected Methods

    /// <summary>
    /// Sets the default values.
    /// </summary>
    /// <remarks>
    /// This method should be overridden to set the default values of properties.
    /// </remarks>
    protected virtual void SetDefaultValues()
    {
    }

    #endregion

    #endregion
}

/// <summary>
/// Defines the configuration used by the application.
/// </summary>
/// <seealso cref="ApplicationConfigurationBase" />
[System.CodeDom.Compiler.GeneratedCode("Lithium", "5")]
internal partial class ApplicationConfiguration : ApplicationConfigurationBase
{
    #region Code

    #region Public Constructors

    /// <summary>
    /// Initializes a new instance of the <see cref="ApplicationConfiguration"/> class.
    /// </summary>
    public ApplicationConfiguration()
        : base()
    {
    }

    #endregion

    #endregion
}

/// <summary>
/// Defines the base class for the configuration of an environment.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("Lithium", "5")]
internal abstract partial class EnvironmentConfigurationBase
{
    #region Code

    #region Public Properties

    /// <summary>
    /// Gets or sets the service base URI.
    /// </summary>
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings")]
    public virtual string? ServiceBaseUri
    {
        get;
        set;
    }

    #endregion

    #region Protected Constructors

    /// <summary>
    /// Initializes a new instance of the <see cref="EnvironmentConfigurationBase"/> class.
    /// </summary>
    protected EnvironmentConfigurationBase()
    {
    }

    #endregion

    #region Protected Methods

    /// <summary>
    /// Sets the default values.
    /// </summary>
    /// <remarks>
    /// This method should be overridden to set the default values of properties.
    /// </remarks>
    protected virtual void SetDefaultValues()
    {
    }

    #endregion

    #endregion
}

/// <summary>
/// Defines the configuration of an environment.
/// </summary>
/// <seealso cref="EnvironmentConfigurationBase" />
[System.CodeDom.Compiler.GeneratedCode("Lithium", "5")]
internal partial class EnvironmentConfiguration : EnvironmentConfigurationBase
{
    #region Code

    #region Public Constructors

    /// <summary>
    /// Initializes a new instance of the <see cref="EnvironmentConfiguration"/> class.
    /// </summary>
    public EnvironmentConfiguration()
        : base()
    {
    }

    #endregion

    #endregion
}

#endregion

#endregion
